wandb_version: 1

checkpoint_root:
  desc: null
  value: /data/zhaobo/zhouyufan/PDPP-Optimize/checkpoint
checkpoint_max_root:
  desc: null
  value: /data/zhaobo/zhouyufan/PDPP-Optimize/save_max
log_root:
  desc: null
  value: /data/zhaobo/zhouyufan/PDPP-Optimize/log/log
checkpoint_dir:
  desc: null
  value: whl
optimizer:
  desc: null
  value: adam
num_thread_reader:
  desc: null
  value: 8
batch_size:
  desc: null
  value: 256
batch_size_val:
  desc: null
  value: 256
momemtum:
  desc: null
  value: 0.9
save_freq:
  desc: null
  value: 1
crop_only:
  desc: null
  value: 1
centercrop:
  desc: null
  value: 0
random_flip:
  desc: null
  value: 1
verbose:
  desc: null
  value: 1
fps:
  desc: null
  value: 1
cudnn_benchmark:
  desc: null
  value: 1
dataset:
  desc: null
  value: crosstask_how
action_dim:
  desc: null
  value: 105
observation_dim:
  desc: null
  value: 1536
class_dim:
  desc: null
  value: 18
root:
  desc: null
  value: /data/zhaobo/zhouyufan/PDPP-Optimize/dataset/crosstask
json_path_train:
  desc: null
  value: /data/zhaobo/zhouyufan/PDPP-Optimize/dataset/crosstask/crosstask_release/train_list.json
json_path_val:
  desc: null
  value: /data/zhaobo/zhouyufan/PDPP-Optimize/dataset/crosstask/crosstask_release/test_list.json
json_path_val2:
  desc: null
  value: /data/zhaobo/zhouyufan/PDPP-Optimize/dataset/crosstask/crosstask_release/output6.json
n_train_steps:
  desc: null
  value: 250
start_epoch:
  desc: null
  value: 0
resume:
  desc: null
  value: false
resume_path:
  desc: null
  value: None
evaluate:
  desc: null
  value: true
pretrained:
  desc: null
  value: false
pin_memory:
  desc: null
  value: true
world_size:
  desc: null
  value: 1
rank:
  desc: null
  value: 0
dist_file:
  desc: null
  value: dist-file
dist_backend:
  desc: null
  value: nccl
multiprocessing_distributed:
  desc: null
  value: false
name:
  desc: null
  value: howpredictor13
ckpt_path:
  desc: null
  value: ''
dist_port:
  desc: null
  value: 21712
log_freq:
  desc: null
  value: 500
gpu:
  desc: null
  value: 5
seed:
  desc: null
  value: 1111
weight:
  desc: null
  value: 6
clip_denoised:
  desc: null
  value: true
ddim_discr_method:
  desc: null
  value: uniform
lr:
  desc: null
  value: 0.0005
ema_decay:
  desc: null
  value: 0.995
gradient_accumulate_every:
  desc: null
  value: 1
step_start_ema:
  desc: null
  value: 400
update_ema_every:
  desc: null
  value: 10
ie_num:
  desc: null
  value: 2
transformer_num:
  desc: null
  value: 5
base_model:
  desc: null
  value: predictor
classfier_model:
  desc: null
  value: transformer
n_diffusion_steps:
  desc: null
  value: 250
num_heads:
  desc: null
  value: 4
num_layers:
  desc: null
  value: 2
dim_feedforward:
  desc: null
  value: 1024
dropout:
  desc: null
  value: 0.4
horizon:
  desc: null
  value: 6
epochs:
  desc: null
  value: null
if_jump:
  desc: null
  value: 1
loss_type:
  desc: null
  value: Weighted_Gradient_MSE
kind:
  desc: null
  value: 0
l_order:
  desc: null
  value: 1000.0
l_pos:
  desc: null
  value: 1.0
l_perm:
  desc: null
  value: 1.0
ifMask:
  desc: null
  value: true
scale1:
  desc: null
  value: 1/6
scale2:
  desc: null
  value: 1/4
schedule:
  desc: null
  value: not
distributed:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.7
    framework: huggingface
    huggingface_version: 4.44.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1726503079
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 105
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 105
      3:
      - 1
      - 13
      - 16
      - 23
      4: 3.10.14
      5: 0.17.7
      6: 4.44.0
      8:
      - 5
      13: linux-x86_64
